<?php

/**
 * Implementation of hook_wysiwyg_plugin().
 */
function footnotes_wysiwyg_wysiwyg_plugin($editor, $version) {
  $plugin = array(
    'footnotes' => array(
      'buttons' => array('footnotes' => t('Add Footnote')),
      // This is annoying since it entices you to click on the link in 
      // admin/settings/wysiwyg/profile/2/edit and if you do, you lose all unsaved settings.
      // 'url' => 'http://drupal.org/project/footnotes', 
      'extended_valid_elements' => array('fn'),
      'basePath' => base_path(),
      // This is a hack, the plugin is not loaded without this. (no button shows up.)
      // wysiwyg_tinymce_plugin_settings() removes plugins that have empty($plugin['load'])
      // I'm assuming the wysiwyg module should actually set this for plugins it wants to load?
      // Since there aren't many native external TinyMCE plugins currently, this is likely a bug nobody has noticed.
      'load' => 1 
    ),
  );
  switch ($editor) {
    case 'tinymce':
      if ($version > 3) {
        $plugin['footnotes']['path'] = drupal_get_path('module', 'footnotes_wysiwyg') . '/tinymce_plugin/editor_plugin.js';
        return $plugin;
      }
      break;
    case 'ckeditor':
      // For CKEditor, path must be to the directory, not the .js file. The .js file must be called 'plugin.js'.
      // (If including filename here, images to the buttons (defined in js/css) 
      // are lost because they are appended to this path.)
      $plugin['footnotes']['path'] = drupal_get_path('module', 'footnotes_wysiwyg') . '/ckeditor_plugin/';
      return $plugin;
      break;
  }
}

