<?php
/**
 * Implementation of hook_wysiwyg_plugin().
 */
function tinymce_footnotes_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    case 'tinymce':
      if ($version > 3) {
        return array(
            'tinymce_footnotes' => array(
            'path' => drupal_get_path('module', 'tinymce_footnotes') .'/tinymce_plugin/editor_plugin.js',
            'buttons' => array('tinymce_footnotes' => t('Add Footnote')),
            'url' => 'http://drupal.org/project/footnotes',
            'extended_valid_elements' => array('fn'),
            'basePath' => base_path(),
            // This is a hack, the plugin is not loaded without this. (no button shows up.)
            // wysiwyg_tinymce_plugin_settings() removes plugins that have empty($plugin['load'])
            // I'm assuming the wysiwyg module should actually set this for plugins it wants to load?
            // Since there aren't many native external TinyMCE plugins currently, this is likely a bug nobody has noticed.
            'load' => 1 
          ),
        );
      }
      break;
  }
}


