<?php

/**
 * @file
 * Declare the view API in use.
 */

/**
 * Implements hook_views_api().
 */
function footnotes_views_views_api() {
  $view = array(
    'api' => 3.0,
    'path' => backdrop_get_path('module', 'footnotes_views') . '/views',
  );
  return $view;
}

/**
 * Implements hook_autoload_info().
 */
function footnotes_views_autoload_info() {
  return array(
    'footnotes_views_handler_field_body_content' => 'views/footnotes_views_handler_field_body_content.inc',
    'footnotes_views_handler_field_body_footnotes' => 'views/footnotes_views_handler_field_body_footnotes.inc',
  );
}
