<?php

/**
 * @file
 * Hooks and general logic for the Footnotes field module.
 */

/**
 * Implements hook_menu().
 */
function footnotes_field_menu() {
  $items['admin/config/content/footnotes'] = array(
    'title' => 'Footnotes',
    'description' => 'Config page for footnotes fields/blocks',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('_footnotes_field_admin_form'),
    'access arguments' => array('administer footnotes fields'),
    'file' => 'includes/footnotes_field.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function footnotes_field_permission() {
  return array(
    'administer footnotes fields' => array(
      'title' => t('Administer footnotes fields'),
      'description' => t('Perform administration tasks for footnotes fields.'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function footnotes_field_block_info() {
  $blocks['footnotes'] = array(
    'info' => t('Footnotes: node detail'),
    'required contexts' => array('node' => 'node'),
    'description' => t('A block with all footnotes used in a node.'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function footnotes_field_block_view($delta = '', $settings = array(), $contexts = array()) {
  $block = array();
  switch ($delta) {
    case 'footnotes':
      $node = $contexts['node'];
      $expose_block = config_get('footnotes_field.settings', 'expose_block');
      if ($node && !empty($expose_block)) {
        $block['subject'] = t('Footnotes');
        $block['content'] = array(
          '#prefix' => '<div id="footnotes-all">',
          '#markup' => NULL,
          '#suffix' => '</div>',
          '#attached' => array(
            'js' => array(
              array(
                'data' => backdrop_get_path('module', 'footnotes_field') . '/js/footnotes_field.js',
                'type' => 'file',
              ),
            ),
            'css' => array(
              array(
                'data' => backdrop_get_path('module', 'footnotes_field') . '/css/footnotes_field.css',
                'type' => 'file',
              ),
            ),
          ),
        );
        break;
      }
  }
  return $block;
}

/**
 * Implements hook_config_info().
 */
function footnotes_field_config_info() {
  $prefixes['footnotes_field.settings'] = array(
    'label' => t('Module name settings'),
    'group' => t('Configuration'),
  );
}
